USER_FILE_NAME = 'users.txt'
ENQUETE_FILE_NAME = 'enquetes.txt'
TAREFAS_FILE_NAME = 'tarefas.txt'
DASHBOARD_FILE_NAME = 'dashboard.html'
LOGIN_FILE_NAME = 'login.html'
NEW_TASK_FILE_NAME = 'nova-tarefa.html'